'use strict';
function renderApp(){
  const p=data.profile||{};document.getElementById('greeting').textContent=p.displayName?`Olá, ${p.displayName}`:'Health Tracker';document.getElementById('privacyState').textContent=bodyMeasurements().length||labs().length?'Dados privados neste dispositivo':'Nenhum dado privado carregado';renderHome();renderBio();renderEvolution();renderHealth();renderTimeline();
}
function emptyCard(title,text){return `<article class="card"><h2>${esc(title)}</h2><p class="subtle">${esc(text)}</p></article>`;}
function renderHome(){
  const m=latestBody(),chart=document.getElementById('overviewChart');
  if(!m){document.getElementById('heroWeight').textContent='—';document.getElementById('heroDate').textContent='Importe sua base privada para começar';document.getElementById('heroBmi').textContent='—';document.getElementById('heroFatPct').textContent='—';document.getElementById('heroMuscle').textContent='—';document.getElementById('weightDelta').innerHTML='— <small>sem dados</small>';chart.innerHTML='';document.getElementById('overviewLatest').innerHTML='';document.getElementById('homeInsight').textContent='Seus dados de saúde não ficam embutidos no site público. Importe a base privada no menu ⋯.';renderHomeHealth();return;}
  document.getElementById('heroWeight').textContent=fmt(m.weightKg);document.getElementById('heroDate').textContent=`${brDate(m.date)}${m.time?` • ${m.time}`:''}`;document.getElementById('heroBmi').textContent=fmt(metricValue(m,'bmi'));document.getElementById('heroFatPct').textContent=`${fmt(m.bodyFatPct)}%`;document.getElementById('heroMuscle').textContent=`${fmt(m.skeletalMuscleKg)} kg`;
  const base=Number(data.profile?.baselineWeightKg);document.getElementById('weightDelta').innerHTML=Number.isFinite(base)?`↓ ${fmt(base-m.weightKg)} kg <small>vs. ${esc(data.profile?.baselineLabel||'referência')}</small>`:'—';renderHomeChart(chart);document.getElementById('overviewLatest').innerHTML=`<span class="last-chip red"><i></i>Peso <strong>${fmt(m.weightKg)} kg</strong></span><span class="last-chip blue"><i></i>Músculo <strong>${fmt(m.skeletalMuscleKg)} kg</strong></span><span class="last-chip amber"><i></i>Gordura <strong>${fmt(m.bodyFatPct)}%</strong></span>`;
  const f=firstBody(),dw=m.weightKg-f.weightKg,df=m.bodyFatPct-f.bodyFatPct,dm=m.skeletalMuscleKg-f.skeletalMuscleKg;document.getElementById('homeInsight').textContent=`De ${brDate(f.date)} a ${brDate(m.date)}: peso ${signed(dw,' kg')}, gordura ${signed(df,' p.p.')} e massa muscular ${signed(dm,' kg')}.`;renderHomeHealth();
}
function renderHomeHealth(){const box=document.getElementById('healthGlance'),date=latestLabDate();if(!date){box.innerHTML='<p class="subtle">Sem exames privados carregados.</p>';document.getElementById('healthDateBase').textContent='Últimos exames';return;}const keys=['glucose','hba1c','hdl','ldl','triglycerides','testosterone_total'];box.innerHTML=keys.map(k=>latestLab(k)).filter(Boolean).map(x=>{const st=labStatus(x);return `<div class="health-mini"><span>${esc(x.label)}</span><strong>${fmtFlex(x.value)} ${esc(x.unit||'')}</strong><small class="status ${st.code}">${esc(st.label)}</small></div>`;}).join('');document.getElementById('healthDateBase').textContent=`Data-base: ${brDate(date)}`;}

function renderBio(){const box=document.getElementById('resultsTimeline'),rows=bodyMeasurements();if(!rows.length){box.innerHTML=emptyCard('Sem bioimpedâncias','Importe sua base privada no menu ⋯.');return;}box.innerHTML=[...rows].reverse().map(m=>`<button class="timeline-item result-click" data-body-id="${esc(m.id)}"><div class="timeline-date"><div><strong>${m.date.slice(8)}</strong><small>${['','jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'][Number(m.date.slice(5,7))]}</small></div></div><div><h3>${brDate(m.date)}${m.time?` • ${m.time}`:''}</h3><div class="timeline-metrics"><span><b>${fmt(m.weightKg)}</b> kg</span><span><b>${fmt(m.skeletalMuscleKg)}</b> kg músculo</span><span><b>${fmt(m.bodyFatPct)}</b>% gordura</span></div></div><div class="timeline-score">${m.score?`${m.score}<small>/100</small>`:'›'}</div></button>`).join('');}

function openBodyDetail(id){const m=bodyMeasurements().find(x=>x.id===id);if(!m)return;const main=[['Peso',m.weightKg,'kg','weightKg'],['IMC',metricValue(m,'bmi'),'','bmi'],['Gordura corporal',m.bodyFatPct,'%','bodyFatPct'],['Massa muscular',m.skeletalMuscleKg,'kg','skeletalMuscleKg'],['Massa de gordura',m.fatMassKg,'kg','fatMassKg'],['Água corporal',m.bodyWaterL,'L','bodyWaterL']].filter(x=>x[1]!=null);const more=[['Proteína',m.proteinKg,'kg','proteinKg'],['Minerais',m.mineralsKg,'kg','mineralsKg'],['Massa livre de gordura',m.fatFreeMassKg,'kg'],['Metabolismo basal',m.bmrKcal,'kcal'],['Relação cintura-quadril',m.waistHipRatio,'','waistHipRatio'],['Gordura visceral',m.visceralFatLevel,'','visceralFatLevel'],['Grau de obesidade',m.obesityDegreePct,'%','obesityDegreePct']].filter(x=>x[1]!=null);
  const metricCard=([label,val,unit,key])=>{const range=key?m.referenceRanges?.[key]:null;return `<div class="detail-metric"><span>${esc(label)}</span><strong>${fmtFlex(val)}${unit?` ${esc(unit)}`:''}</strong><small>${range?`${fmtFlex(range[0])} – ${fmtFlex(range[1])} · ${bodyStatus(val,range)}`:'registrado'}</small></div>`;};
  let html=`<div class="detail-score"><div><span>Pontuação InBody</span><strong>${m.score!=null?m.score:'—'}<small>/100</small></strong></div><p>${brDate(m.date)}${m.time?` · ${m.time}`:''}</p></div><h3>Visão geral</h3><div class="detail-grid">${main.map(metricCard).join('')}</div>`;
  if(more.length)html+=`<h3>Composição e outros indicadores</h3><div class="detail-grid">${more.map(metricCard).join('')}</div>`;
  if(m.idealWeightKg!=null)html+=`<h3>Controle de peso</h3><div class="control-grid"><div><span>Peso ideal</span><strong>${fmt(m.idealWeightKg)} kg</strong></div><div><span>Controle de peso</span><strong>${signed(m.weightControlKg,' kg')}</strong></div><div><span>Controle de gordura</span><strong>${signed(m.fatControlKg,' kg')}</strong></div><div><span>Controle muscular</span><strong>${signed(m.muscleControlKg,' kg')}</strong></div></div>`;
  if(m.leanSegments?.length)html+=`<h3>Massa magra segmentar</h3><div class="segment-grid">${m.leanSegments.map(s=>`<div class="segment-box"><span>${esc(segmentName(s.segment||s.name))}</span><strong>${fmtFlex(s.kg)} kg</strong><em>${fmtFlex(s.percentOfReference??s.pct)}%</em></div>`).join('')}</div>`;
  if(m.fatSegments?.length)html+=`<h3>Gordura segmentar</h3><div class="segment-grid">${m.fatSegments.map(s=>`<div class="segment-box"><span>${esc(segmentName(s.segment||s.name))}</span><strong>${fmtFlex(s.kg)} kg</strong><em>${fmtFlex(s.percentOfReference??s.pct)}%</em></div>`).join('')}</div>`;
  document.getElementById('bodyDetailContent').innerHTML=html;document.getElementById('bodyDetailTitle').textContent=`Bioimpedância · ${brDate(m.date)}`;document.getElementById('bodyDetailDialog').showModal();
}
function segmentName(s){return({left_arm:'Braço esquerdo',right_arm:'Braço direito',trunk:'Tronco',left_leg:'Perna esquerda',right_leg:'Perna direita'})[s]||s;}

function renderEvolution(){const rows=bodyMeasurements();if(!rows.length){document.getElementById('evolutionChart').innerHTML='';document.getElementById('evoMetricValue').textContent='—';document.getElementById('evoMetricDelta').textContent='—';document.getElementById('evoReference').innerHTML='';return;}const l=rows.at(-1),f=rows[0],lv=Number(metricValue(l,currentBodyMetric)),fv=Number(metricValue(f,currentBodyMetric)),u=bodyMetricUnit(currentBodyMetric);document.getElementById('evoMetricLabel').textContent=bodyMetricLabel(currentBodyMetric);document.getElementById('evoMetricValue').innerHTML=`${fmt(lv)}${u?` <small>${u}</small>`:''}`;document.getElementById('evoMetricDelta').textContent=`${signed(lv-fv,currentBodyMetric==='bodyFatPct'?' p.p.':u?` ${u}`:'')} desde ${brDate(f.date)}`;renderBodyChart(document.getElementById('evolutionChart'),currentBodyMetric);const range=bodyMetricRange(currentBodyMetric),target=bodyMetricTarget(currentBodyMetric);document.getElementById('evoReference').innerHTML=`${range?`<span>Faixa InBody: <strong>${fmtFlex(range[0])} – ${fmtFlex(range[1])} ${u}</strong></span>`:''}${target!=null?`<span>Peso ideal: <strong>${fmtFlex(target)} kg</strong></span>`:''}`;}

function healthExecutiveSummary(){const date=latestLabDate(),fresh=freshness(date),latest=latestLabsByKey(),attention=latest.filter(x=>['high','low'].includes(labStatus(x).code)),context=latest.filter(x=>labStatus(x).code==='context');const positives=[];for(const k of ['glucose','hba1c','triglycerides','creatinine','vitamin_d_25oh']){const x=latestLab(k);if(x&&labStatus(x).code==='ok')positives.push(x.label);}let narrative=date?`Leitura baseada nos resultados mais recentes até ${brDate(date)}. `:'Nenhum resultado laboratorial carregado. ';if(positives.length)narrative+=`${positives.slice(0,4).join(', ')} estão dentro das referências disponíveis. `;if(attention.length)narrative+=`${attention.map(x=>x.label).slice(0,3).join(', ')} merecem atenção em relação à referência do próprio exame. `;if(context.length)narrative+=`Alguns marcadores exigem contexto clínico ou de tratamento.`;return{date,fresh,attention,context,narrative};}
function renderHealth(){const labsAll=labs(),summary=healthExecutiveSummary();document.getElementById('healthSummaryText').textContent=summary.narrative;document.getElementById('healthSummaryDate').textContent=summary.date?`Data-base ${brDate(summary.date)}`:'Sem data-base';document.getElementById('healthFreshness').className=`freshness ${summary.fresh.code}`;document.getElementById('healthFreshness').textContent=summary.fresh.label;document.getElementById('healthKpis').innerHTML=`<div><span>Resultados</span><strong>${labsAll.length}</strong></div><div><span>Atenção</span><strong>${summary.attention.length}</strong></div><div><span>Contextuais</span><strong>${summary.context.length}</strong></div>`;
  const cats=CATEGORY_ORDER.filter(c=>labKeys().some(k=>labCategory(k)===c));if(cats.length&&!cats.includes(currentHealthCategory))currentHealthCategory=cats[0];document.getElementById('healthCategoryTabs').innerHTML=cats.map(c=>`<button class="${c===currentHealthCategory?'active':''}" data-health-cat="${c}">${CATEGORY_LABELS[c]}</button>`).join('');const keys=labKeys().filter(k=>labCategory(k)===currentHealthCategory);if(keys.length&&!keys.includes(currentLabKey))currentLabKey=keys[0];document.getElementById('healthMarkers').innerHTML=keys.map(k=>{const x=latestLab(k),st=labStatus(x);return `<button class="marker-row ${k===currentLabKey?'active':''}" data-lab-key="${esc(k)}"><div><strong>${esc(x.label)}</strong><small>${brDate(x.date)} · ${esc(markerReferenceText(x))}</small></div><div><b>${fmtFlex(x.value)} ${esc(x.unit||'')}</b><em class="status ${st.code}">${esc(st.label)}</em></div></button>`;}).join('')||'<p class="subtle">Sem marcadores nesta categoria.</p>';renderSelectedLab();renderReportsAndTimeline();}
function renderSelectedLab(){const s=labSeries(currentLabKey),last=s.at(-1);if(!last){document.getElementById('labMetricLabel').textContent='Exame';document.getElementById('labMetricValue').textContent='—';document.getElementById('labMetricDelta').textContent='—';document.getElementById('labReference').textContent='—';document.getElementById('labContext').textContent='';document.getElementById('labChart').innerHTML='';document.getElementById('labHistory').innerHTML='';return;}const st=labStatus(last);document.getElementById('labMetricLabel').textContent=last.label;document.getElementById('labMetricValue').innerHTML=`${fmtFlex(last.value)} <small>${esc(last.unit||'')}</small>`;document.getElementById('labMetricDelta').textContent=s.length>1&&Number.isFinite(Number(last.value))&&Number.isFinite(Number(s.at(-2).value))?`${signed(Number(last.value)-Number(s.at(-2).value))} desde ${brDate(s.at(-2).date)}`:`${brDate(last.date)} · ${st.label}`;document.getElementById('labReference').textContent=markerReferenceText(last);document.getElementById('labContext').textContent=last.context||last.reference?.note||'';renderLabChartV5(document.getElementById('labChart'),s);document.getElementById('labHistory').innerHTML=[...s].reverse().map(x=>{const sx=labStatus(x);return `<div class="lab-history-row"><time>${brDate(x.date)}</time><div><strong>${fmtFlex(x.value)} ${esc(x.unit||'')}</strong><small>${esc(markerReferenceText(x))}</small></div><em class="status ${sx.code}">${esc(sx.label)}</em></div>`;}).join('');}
function renderReportsAndTimeline(){const box=document.getElementById('reportHistory'),rs=reports();box.innerHTML=rs.map(r=>`<article class="report-item"><div><span class="report-tag">${esc(r.category||'Laudo')}</span><time>${r.date?brDate(r.date):'Data não recuperada'}</time></div><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p><small>Fonte: ${esc(r.source||'histórico')}</small></article>`).join('')||'<p class="subtle">Sem laudos carregados.</p>';}

function renderTimeline(){const box=document.getElementById('clinicalTimeline'),events=timelineEvents();box.innerHTML=events.map(e=>`<article class="clinical-event"><div class="event-dot ${esc(e.type)}"></div><div><time>${brDate(e.date)}</time><h3>${esc(e.title)}</h3><p>${esc(e.summary||'')}</p></div></article>`).join('')||emptyCard('Linha do tempo vazia','Importe sua base privada.');}
