function render(){
  measurements.sort(byDate);labs.sort(byLabDate);
  document.getElementById('greeting').textContent=profile.displayName?`Olá, ${profile.displayName} 👋`:'Olá 👋';
  if(hasData()){renderHome();renderResults();renderEvolution();renderCompare()}else renderEmptyBody();
  renderHealthGlance();renderHealth();
}
function renderEmptyBody(){
  document.getElementById('heroWeight').textContent='—';document.getElementById('heroDate').textContent='Nenhuma medição carregada';document.getElementById('heroBmi').textContent='—';document.getElementById('heroFatPct').textContent='—';document.getElementById('heroMuscle').textContent='—';
  document.getElementById('heroBmiStatus').textContent='—';document.getElementById('heroFatStatus').textContent='—';document.getElementById('heroMuscleStatus').textContent='—';document.getElementById('weightDelta').innerHTML='— <small>sem referência</small>';
  ['summaryWeightChange','summaryFatChange','summaryMuscleChange'].forEach(id=>document.getElementById(id).textContent='—');['summaryWeightLabel','summaryFatLabel','summaryMuscleLabel'].forEach(id=>document.getElementById(id).textContent='Período');
  document.getElementById('quickInsightTitle').textContent='Carregue seus dados para começar.';document.getElementById('quickInsight').textContent='Use o menu ⋯ para importar seu histórico completo.';document.getElementById('overviewChart').innerHTML='';
  document.getElementById('compositionList').innerHTML='<p class="subtle">Nenhuma medição disponível.</p>';document.getElementById('scoreBadge').textContent='—/100';['idealWeight','weightControl','fatControl','muscleControl'].forEach(id=>document.getElementById(id).textContent='—');
  document.getElementById('leanSegments').innerHTML='<p class="subtle">Nenhuma medição disponível.</p>';document.getElementById('fatSegments').innerHTML='<p class="subtle">Nenhuma medição disponível.</p>';document.getElementById('resultsTimeline').innerHTML='<article class="card"><h2>Seu histórico está vazio</h2><p class="subtle">Importe seu backup ou adicione uma medição.</p></article>';
  document.getElementById('evoMetricValue').textContent='—';document.getElementById('evoMetricDelta').textContent='—';document.getElementById('evolutionChart').innerHTML='';document.getElementById('comparisonIndicators').innerHTML='';document.getElementById('compareA').innerHTML='<option>Sem dados</option>';document.getElementById('compareB').innerHTML='<option>Sem dados</option>';document.getElementById('compareGrid').innerHTML='';
}
function renderHome(){
  const l=latest(),f=first();
  document.getElementById('heroWeight').textContent=fmt(l.weight);document.getElementById('heroDate').textContent=`${brDate(l.date)}${l.time?` • ${l.time}`:''}`;document.getElementById('heroBmi').textContent=fmt(metricValue(l,'bmi'));document.getElementById('heroFatPct').textContent=`${fmt(l.fatPct)}%`;document.getElementById('heroMuscle').textContent=`${fmt(l.muscle)} kg`;
  document.getElementById('heroBmiStatus').textContent=rangeStatus(metricValue(l,'bmi'),l.ranges?.bmi);document.getElementById('heroFatStatus').textContent=rangeStatus(l.fatPct,l.ranges?.fatPct);document.getElementById('heroMuscleStatus').textContent=rangeStatus(l.muscle,l.ranges?.muscle);
  const ref=Number(profile.referenceWeight);if(Number.isFinite(ref)){const d=ref-l.weight;document.getElementById('weightDelta').innerHTML=`${d>=0?'↓':'↑'} ${fmt(Math.abs(d))} kg <small>vs. ${escapeHtml(profile.referenceLabel||'referência')}</small>`}else document.getElementById('weightDelta').innerHTML=`${measurements.length>1?signed(l.weight-f.weight,' kg'):'Primeira medição'}<small>${measurements.length>1?`vs. ${brDate(f.date)}`:''}</small>`;
  const dw=delta(l.weight,f.weight),df=delta(l.fatPct,f.fatPct),dm=delta(l.muscle,f.muscle);document.getElementById('summaryWeightChange').textContent=signed(dw,' kg');document.getElementById('summaryFatChange').textContent=signed(df,' p.p.');document.getElementById('summaryMuscleChange').textContent=signed(dm,' kg');const pl=`Desde ${shortDate(f.date)}`;['summaryWeightLabel','summaryFatLabel','summaryMuscleLabel'].forEach(id=>document.getElementById(id).textContent=pl);
  document.getElementById('quickInsightTitle').textContent='Sua evolução em contexto.';document.getElementById('quickInsight').textContent=measurements.length>1?`Entre ${brDate(f.date)} e ${brDate(l.date)}, o peso variou ${signed(dw,' kg')}, a gordura ${signed(df,' p.p.')} e a massa muscular ${signed(dm,' kg')}.`:'Primeira medição registrada.';
  renderMultiChart(document.getElementById('overviewChart'));renderComposition();renderSegments();
}
function renderComposition(){
  const l=latest();const items=[['Peso',l.weight,'kg',l.ranges?.weight],['Massa muscular',l.muscle,'kg',l.ranges?.muscle],['Gordura corporal',l.fatPct,'%',l.ranges?.fatPct],['Massa de gordura',l.fatMass,'kg',l.ranges?.fatMass],['Água corporal',l.water,'L',l.ranges?.water],['Proteína',l.protein,'kg',l.ranges?.protein],['Minerais',l.minerals,'kg',l.ranges?.minerals],['Massa livre de gordura',l.ffm,'kg',null],['Metabolismo basal',l.bmr,'kcal',null],['Relação cintura-quadril',l.waistHip,'',l.ranges?.waistHip],['Gordura visceral',l.visceral,'',l.ranges?.visceral],['Grau de obesidade',l.obesity,'%',l.ranges?.obesity]];
  document.getElementById('compositionList').innerHTML=items.filter(x=>x[1]!=null).map(([name,val,unit,range])=>`<div class="composition-item"><span>${name}</span><strong>${fmt(val,Number.isInteger(val)?0:(name==='Minerais'||name.includes('cintura'))?2:1)}${unit?` ${unit}`:''}</strong><small>${range?`${fmtFlexible(range[0])} – ${fmtFlexible(range[1])}`:'registrado'}</small></div>`).join('');
  document.getElementById('scoreBadge').textContent=l.score!=null?`${l.score}/100`:'—/100';document.getElementById('idealWeight').textContent=l.idealWeight!=null?`${fmt(l.idealWeight)} kg`:'—';document.getElementById('weightControl').textContent=l.weightControl!=null?signed(l.weightControl,' kg'):'—';document.getElementById('fatControl').textContent=l.fatControl!=null?signed(l.fatControl,' kg'):'—';document.getElementById('muscleControl').textContent=l.muscleControl!=null?signed(l.muscleControl,' kg'):'—';
}
function renderSegments(){const l=latest();const box=x=>`<div class="segment-box"><div class="top"><div><span>${x.name}</span><strong>${fmt(x.kg,x.kg<4?2:1)} kg</strong></div><em>${fmt(x.pct)}%</em></div></div>`;document.getElementById('leanSegments').innerHTML=(l.leanSegments||[]).map(box).join('')||'<p class="subtle">Sem dados segmentares.</p>';document.getElementById('fatSegments').innerHTML=(l.fatSegments||[]).map(box).join('')||'<p class="subtle">Sem dados segmentares.</p>'}
function renderResults(){document.getElementById('resultsTimeline').innerHTML=[...measurements].reverse().map(m=>{const[y,mo,d]=m.date.split('-');return `<article class="timeline-item"><div class="timeline-date"><div><strong>${d}</strong><small>${['','jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'][Number(mo)]}</small></div></div><div><h3>${brDate(m.date)}${m.time?` • ${m.time}`:''}</h3><div class="timeline-metrics"><span><b>${fmt(m.weight)}</b> kg</span><span><b>${fmt(m.muscle)}</b> kg músculo</span><span><b>${fmt(m.fatPct)}</b>% gordura</span></div></div><div class="timeline-score">${m.score?`${m.score}<small>/100</small>`:'›'}</div></article>`}).join('')}
function renderEvolution(){if(!hasData())return;const l=latest(),f=first(),lv=metricValue(l,currentMetric),fv=metricValue(f,currentMetric),d=delta(lv,fv),unit=metricUnit(currentMetric);document.getElementById('evoMetricLabel').textContent=metricLabel(currentMetric);document.getElementById('evoMetricValue').innerHTML=`${fmt(lv)} ${unit?`<small>${unit}</small>`:''}`;document.getElementById('evoMetricDelta').textContent=`${signed(d,currentMetric==='fatPct'?' p.p.':unit?` ${unit}`:'')} desde ${brDate(f.date)}`;renderSingleChart(document.getElementById('evolutionChart'),currentMetric);document.getElementById('comparisonIndicators').innerHTML=['weight','muscle','fatPct','bmi'].map(k=>{const a=metricValue(f,k),b=metricValue(l,k);if(a==null||b==null)return'';const dd=delta(b,a),su=k==='fatPct'?' p.p.':metricUnit(k)?` ${metricUnit(k)}`:'';return `<div class="indicator-row"><span>${metricLabel(k)}</span><strong>${signed(dd,su)}</strong><small>${signed((dd/a)*100,'%')}</small></div>`}).join('')}
function renderCompare(){if(!hasData())return;const aSel=document.getElementById('compareA'),bSel=document.getElementById('compareB'),prevA=aSel.value||measurements[0].id,prevB=bSel.value||latest().id,opts=measurements.map(m=>`<option value="${m.id}">${brDate(m.date)} • ${fmt(m.weight)} kg</option>`).join('');aSel.innerHTML=opts;bSel.innerHTML=opts;aSel.value=measurements.some(x=>x.id===prevA)?prevA:measurements[0].id;bSel.value=measurements.some(x=>x.id===prevB)?prevB:latest().id;renderCompareGrid()}
function renderCompareGrid(){if(!hasData())return;const a=measurements.find(x=>x.id===document.getElementById('compareA').value)||first(),b=measurements.find(x=>x.id===document.getElementById('compareB').value)||latest(),defs=[['Peso','weight','kg'],['Massa muscular','muscle','kg'],['Gordura corporal','fatPct','%'],['IMC','bmi',''],['Massa de gordura','fatMass','kg'],['Gordura visceral','visceral',''],['Água corporal','water','L'],['Metabolismo basal','bmr','kcal']];document.getElementById('compareGrid').innerHTML=defs.map(([label,k,u])=>{const av=metricValue(a,k),bv=metricValue(b,k);if(av==null||bv==null)return'';const d=Number((bv-av).toFixed(k==='bmr'?0:1));return `<article class="compare-card"><span>${label}</span><strong>${fmt(bv,k==='bmr'?0:1)}${u?` ${u}`:''}</strong><em class="neutral">${signed(d,k==='fatPct'?' p.p.':u?` ${u}`:'')}</em><span> vs. ${fmt(av,k==='bmr'?0:1)}${u?` ${u}`:''}</span></article>`}).join('')}

function renderHealthGlance(){const box=document.getElementById('healthGlance');if(!labs.length){box.innerHTML='<p class="subtle">Nenhum exame carregado. Importe o backup V3 para visualizar seu painel de saúde.</p>';return}const keys=['glucose','hdl','ldl','triglycerides'];box.innerHTML=keys.map(k=>{const x=latestLab(k);if(!x)return'';return `<div class="health-mini"><span>${LAB_DEFS[k].label}</span><strong>${fmtFlexible(x.value)} ${escapeHtml(x.unit||LAB_DEFS[k].unit)}</strong><small>${brDate(x.date)}</small></div>`}).join('')}
function renderHealth(){
  document.getElementById('labCountBadge').textContent=String(labs.length);
  const keys=Object.keys(LAB_DEFS);const available=keys.filter(k=>labSeries(k).length);if(!available.length){document.getElementById('healthSummaryGrid').innerHTML='<p class="subtle">Nenhum resultado laboratorial carregado.</p>';document.getElementById('labMetricTabs').innerHTML='';document.getElementById('labMetricLabel').textContent='Exame';document.getElementById('labMetricValue').textContent='—';document.getElementById('labMetricDelta').textContent='—';document.getElementById('labChart').innerHTML='';document.getElementById('labHistory').innerHTML='<div class="lab-empty">Importe o backup V3 ou adicione seus exames manualmente.</div>';return}
  if(!available.includes(currentLabMetric))currentLabMetric=available[0];
  document.getElementById('healthSummaryGrid').innerHTML=available.map(k=>{const x=latestLab(k);return `<div class="health-summary-card"><span>${LAB_DEFS[k].label}</span><strong>${fmtFlexible(x.value)} ${escapeHtml(x.unit||LAB_DEFS[k].unit)}</strong><small>Último: ${brDate(x.date)}</small></div>`}).join('');
  document.getElementById('labMetricTabs').innerHTML=available.map(k=>`<button class="${k===currentLabMetric?'active':''}" data-lab-metric="${k}">${LAB_DEFS[k].label}</button>`).join('');
  document.querySelectorAll('[data-lab-metric]').forEach(b=>b.addEventListener('click',()=>{currentLabMetric=b.dataset.labMetric;renderHealth()}));
  const s=labSeries(currentLabMetric),last=s.at(-1),prev=s.at(-2);document.getElementById('labMetricLabel').textContent=LAB_DEFS[currentLabMetric].label;document.getElementById('labMetricValue').innerHTML=`${fmtFlexible(last.value)} <small>${escapeHtml(last.unit||LAB_DEFS[currentLabMetric].unit)}</small>`;document.getElementById('labMetricDelta').textContent=prev?`${signed(last.value-prev.value,'')} desde ${brDate(prev.date)}`:`Resultado de ${brDate(last.date)}`;renderLabChart(document.getElementById('labChart'),s,currentLabMetric);
  document.getElementById('labHistory').innerHTML=[...labs].reverse().map(x=>`<div class="lab-history-row"><time>${brDate(x.date)}</time><strong>${LAB_DEFS[x.key]?.label||escapeHtml(x.key)}</strong><span>${fmtFlexible(x.value)} ${escapeHtml(x.unit||LAB_DEFS[x.key]?.unit||'')}</span></div>`).join('');
}
