// Navegação e interações
document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.nav)));
document.getElementById('openEvolutionBtn').addEventListener('click',()=>navigate('evolution'));document.getElementById('openHealthBtn').addEventListener('click',()=>navigate('health'));
document.querySelectorAll('#homeSegments button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#homeSegments button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.home-panel').forEach(p=>p.classList.remove('active'));document.getElementById('home'+b.dataset.homeTab[0].toUpperCase()+b.dataset.homeTab.slice(1)).classList.add('active')}));
document.querySelectorAll('#metricTabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#metricTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentMetric=b.dataset.metric;renderEvolution()}));document.getElementById('compareA').addEventListener('change',renderCompareGrid);document.getElementById('compareB').addEventListener('change',renderCompareGrid);

const mDialog=document.getElementById('measurementDialog');function openAdd(){const d=new Date(),f=document.getElementById('measurementForm');f.reset();f.elements.date.value=d.toISOString().slice(0,10);f.elements.time.value=d.toTimeString().slice(0,5);mDialog.showModal()}document.getElementById('addMeasurementBtn').addEventListener('click',openAdd);document.getElementById('fabAdd').addEventListener('click',openAdd);document.getElementById('measurementForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target),obj={id:`${fd.get('date')}-${Date.now()}`,date:fd.get('date'),time:fd.get('time')||null};['weight','muscle','fatPct','bmi','fatMass','water','bmr','visceral'].forEach(k=>{const v=fd.get(k);if(v!=='')obj[k]=Number(v)});measurements.push(obj);measurements.sort(byDate);saveData();mDialog.close();render();navigate('results')});

const labDialog=document.getElementById('labDialog');document.getElementById('addLabBtn').addEventListener('click',()=>{const f=document.getElementById('labForm');f.reset();f.elements.date.value=new Date().toISOString().slice(0,10);f.elements.unit.value='mg/dL';labDialog.showModal()});document.getElementById('labForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);labs.push({id:`lab-${Date.now()}`,date:fd.get('date'),key:fd.get('key'),value:Number(fd.get('value')),unit:fd.get('unit')||LAB_DEFS[fd.get('key')].unit});labs.sort(byLabDate);saveData();labDialog.close();render();navigate('health')});

const dataDialog=document.getElementById('dataDialog');document.getElementById('settingsBtn').addEventListener('click',()=>dataDialog.showModal());document.getElementById('closeDataDialog').addEventListener('click',()=>dataDialog.close());document.getElementById('exportBtn').addEventListener('click',()=>{if(!measurements.length&&!labs.length){alert('Nenhum dado para exportar.');return}const payload={schemaVersion:SCHEMA_VERSION,exportedAt:new Date().toISOString(),profile,measurements,labs},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`health-tracker-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)});document.getElementById('importInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const payload=importPayload(JSON.parse(await file.text()));if(!validateMeasurements(payload.measurements))throw new Error('Bioimpedâncias inválidas');if(!validateLabs(payload.labs))throw new Error('Exames inválidos');profile=payload.profile||{};measurements=payload.measurements.sort(byDate);labs=payload.labs.sort(byLabDate);saveData();render();dataDialog.close();alert('Histórico importado com sucesso.')}catch(err){console.warn(err);alert('Não foi possível importar este arquivo.')}finally{e.target.value=''}});document.getElementById('resetBtn').addEventListener('click',()=>{if(confirm('Apagar todos os dados salvos neste aparelho?')){measurements=[];labs=[];profile={};localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(LEGACY_STORAGE_KEY);render();dataDialog.close()}});

render();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
